import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../globals.css'
import ClientLayout from './ClientLayout'
import { cookies } from 'next/headers'
import jwt from 'jsonwebtoken'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'ft_trans',
  description: 'Generated by create next app',
}

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = await cookies()
  const accessToken = cookieStore.get('accessToken')
  let user = null

  try {
    if (accessToken) {
      user = jwt.verify(accessToken.value, process.env.JWT_SECRET!)
    }
  } catch (error) {
    console.error('Auth error:', error)
    cookieStore.delete('accessToken')
  }

  return (
    <ClientLayout user={user}>
      <main>{children}</main>
    </ClientLayout>
  )
}
